#pragma once
// From glfw3.h
#define MIKU_MOUSE_BUTTON_1         0
#define MIKU_MOUSE_BUTTON_2         1
#define MIKU_MOUSE_BUTTON_3         2
#define MIKU_MOUSE_BUTTON_4         3
#define MIKU_MOUSE_BUTTON_5         4
#define MIKU_MOUSE_BUTTON_6         5
#define MIKU_MOUSE_BUTTON_7         6
#define MIKU_MOUSE_BUTTON_8         7
#define MIKU_MOUSE_BUTTON_LAST      MIKU_MOUSE_BUTTON_8
#define MIKU_MOUSE_BUTTON_LEFT      MIKU_MOUSE_BUTTON_1
#define MIKU_MOUSE_BUTTON_RIGHT     MIKU_MOUSE_BUTTON_2
#define MIKU_MOUSE_BUTTON_MIDDLE    MIKU_MOUSE_BUTTON_3